version: '3.5'

services:
  nginx:
    build: ./nginx/
    container_name: nginx_app
    volumes:
      - ./static:/static
      - ./media:/media
    ports:
      - '${PORT:-80}:80'
    depends_on:
      - django

  django:
    build: .
    container_name: django
    expose:
      - '8001'
    volumes:
      - .:/code
      - ../medical_words:/medical_words
    command: "uwsgi --socket :8001 --module simple_search.wsgi:application"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  # For celey settings
  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A simple_search worker -l info
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - django
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A simple_search beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile=
    volumes:
      - .:/code
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - django
      - db
      - redis
